sudo: false
language: node_js
env:
  global:
  - secure: rnfX4sOKXHyDHIHCmH/dNG5VEQx3vc32RTu3YtbUz5uQwUoPhLcor/TacdPLGJ9tSBgVKbxp1CKxBGqxJVUDvo4ES6EUNdn3J/JDQ5CtGIUuPIt1ioryHmWxKGvwS2BO0x33aveKrb+8fMrsoU5qfOFkv2Q6u/X3RxHX0EbXDWjvNHHX1F1Yn/cOx+uVfnKawXJFv8cxcgoY5zKqNYpdJ0oK7Z8rHuRn4Np3c0VHhi6OzlH7fPHTXV8hQAzF4oqWKw/f69R21R/l31CUwN+zz5asec8y4SJ4AiJ9AOm+NR9mJ6m5gmT6qHMwm7wheaJsqOeO9xBOECG+cXs0LXgdL3d2e8SYY6Av/eD/nwK3u8+9UXpGoEUPwckiThCvi61Z4DERD4qvhb6CACgSuHJ1tdQooYi/JmgQVuEHgujKklDMpMICmyhg2FzEEOmfdeLjb7BF4kM+Z2q7Dl3Bx6/R2DQ8sNUAj4o4Tmzln+EQlcYszW/foYq5VlLral9WvqxKpjYeBc3qfmXwN1FNWgvPDUtIZDCnYOHfUghEY60jcaOb+1cLasWRweWPbAP7/8rx2au2DQV7VxCAtx6anovr+4gdDYYoblkynVlO8XamMQ4p8DCmrkzOayrvsftwSGXx1kp4V6PcCrCQaHret9d/Lun0fMFeuMWrdsJIBWZqmks=
  - secure: g+QiCcFHcF50BOcTS/MhiQSb8tN3oLBojwkvIxiyiQbPdctsurK8qu3SlUXPbhM1ZYZAAcibMFYuZ5b40GJh6u44o4dnJk1VdC0TF3N8vM/9Hgz626uuSn0/88GDtF6I1GVat4+1T85ulBWUO8TWVCli36y6u2mktqaWK/ljUryNZlTnK/g2Rylw/anPbD3FTudpXtngdXupv7XG78i51jYVGeB3mLXS7ZRwuP/9Opv+MCKvJZQeIoY0OB8H0Mbwo5sY2Fr8maQtsIEb7RauJGFG62ya6l5BPhE8oDMQsfG1/41uGpEZOVCc5hCbXLyHqUecFLhxSzR3NP0jA0mXoq2x2rKcE44pOMka6EysZrVxZ60G4+/dQ/hDo5Vb5S1VAFxs9HjSU2JRtkWQqU++P6L2HINoL2d+mgZtlDmp1r0bSexLK4gPf9YsjkoTWdYcRabvZ+TMZJySHGKufaXg3MbxKfIxXlXOkIjYKt9ywMgCchVNhbdx9xIVlAQ8uiYZ+tTyrEpuCABWgmk2No1DqHI8nRsj+6Hol4nAwMCCNr4MkAg8H1RGMzFD8VKIkbtA5OJe6gEZ2wxD3a6Oz7kNWS23LEz1yppfH4xDO51Zf9+KIcpxnmDLw4+CCyIUhA4W2Tnktk1TLwsx3RxmpdWZEnFUmp2JXzTpDbnOBWVgRHw=
before_install:
- rvm install 2.3.1
- npm i -g grunt-cli
- export PATH=$HOME/.local/bin:${PATH}
install:
- npm i
script:
- if [[ $TRAVIS_BRANCH == "master" ]]; then grunt build && grunt deploy --bucket=dasmicrobot.com;
  else grunt build; fi;
